import Head from 'next/head'
import { MainPage } from '../src/components/MainPage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Benx Nik Task</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <MainPage />
      </main>
    </div>
  )
}
